<Project>
  <PropertyGroup>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
	<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.6.26359.118" />
	<PackageVersion Include="Microsoft.Extensions.Logging" Version="11.0.0-preview.6.26359.118" />
	<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
	<PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
	<PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
	<PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
	<PackageVersion Include="Silk.NET.WebGPU" Version="2.23.0" />
	<PackageVersion Include="Silk.NET.Windowing" Version="2.23.0" />
	<PackageVersion Include="xunit" Version="2.9.3" />
	<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.1" />
  </ItemGroup>
</Project>
