<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spark.Engine\Spark.Engine.csproj" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

</Project>
